baseURL = "http://example.org/"
languageCode = "en-us"
title = "Convox Praxis"
theme = "docuapi"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true

# Configure the language example tabs.
[[params.language_tabs]]
name = "API"
key = "shell"
[[params.language_tabs]]
name = "Go"
key = "go"
